# Generated by Django 5.2.17 on 2026-08-22 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('mapping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_version', models.PositiveIntegerField(blank=True, help_text='Snapshot of the template version used, so later edits do not rewrite history.', null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Completed with warnings'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=8)),
                ('members_processed', models.PositiveIntegerField(default=0)),
                ('dependents_processed', models.PositiveIntegerField(default=0)),
                ('rows_written', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='files.generatedfile')),
                ('mapping_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='mapping.mappingtemplate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to=settings.AUTH_USER_MODEL)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='files.uploadedfile')),
            ],
            options={
                'verbose_name_plural': 'conversion history',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', '-created_at'], name='ch_owner_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'SUCCESS'), _negated=True), ('generated_file__isnull', False), _connector='OR'), name='successful_conversion_has_output', violation_error_message='A successful conversion must reference the workbook it produced.')],
            },
        ),
        migrations.CreateModel(
            name='FileComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_count', models.PositiveIntegerField(default=0)),
                ('terminated_count', models.PositiveIntegerField(default=0)),
                ('changed_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('dropped_count', models.PositiveIntegerField(default=0, help_text='Present in baseline, silently absent from current. On a full file this means termination.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons_as_baseline', to='files.uploadedfile')),
                ('current_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons_as_current', to='files.uploadedfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('baseline_file', 'current_file'), name='uniq_comparison_pair'), models.CheckConstraint(condition=models.Q(('baseline_file', models.F('current_file')), _negated=True), name='comparison_needs_two_files')],
            },
        ),
    ]
