# Generated by Django 5.2.17 on 2026-08-25 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionhistory',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Health plan this record belongs to. Null on rows written before tenancy existed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='users.client'),
        ),
    ]
