# Generated by Django 5.2.17 on 2026-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_conversionhistory_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionhistory',
            name='mapping_snapshot',
            field=models.JSONField(blank=True, default=list, help_text="The exact rules that produced this workbook, frozen at run time. Issue 6.2: the browser sent ad-hoc rules and the run recorded no template at all, so the audit trail said 'converted' without being able to say converted how. A template id and version answer that only while the template still exists; this answers it always."),
        ),
        migrations.AddField(
            model_name='conversionhistory',
            name='mapping_source',
            field=models.CharField(blank=True, help_text='TEMPLATE when a saved template drove the run, INLINE when rules came with the request.', max_length=16),
        ),
    ]
