# Generated by Django 5.2.17 on 2026-08-25 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0003_uploadedfile_conversion_error_and_more'),
        ('users', '0002_backfill_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('VALIDATE', 'Validate 834'), ('CONVERT', 'Convert to Excel')], db_index=True, max_length=16)),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('INTERRUPTED', 'Interrupted')], db_index=True, default='QUEUED', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to='users.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='files.uploadedfile')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', '-created_at'], name='pj_owner_created_idx'), models.Index(fields=['uploaded_file', 'kind', '-created_at'], name='pj_file_kind_idx'), models.Index(fields=['state', 'heartbeat_at'], name='pj_state_heartbeat_idx')],
            },
        ),
    ]
