"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

try:  # optional, only needed for the split-origin dev setup
    import corsheaders  # noqa: F401
    HAS_CORS = True
except ImportError:  # pragma: no cover
    HAS_CORS = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- .env loading ----------------------------------------------------------
#
# Issue 10: .env was documented in .env.example and read by nothing, so every
# value in it was ignored and the committed development SECRET_KEY was the one
# actually in use. Values are loaded here, before any setting is read.
#
# python-dotenv is used when it is installed and a small reader stands in when
# it is not, so a deployment that forgets one pip install does not silently
# fall back to development defaults again.

def _load_env_file(path):
    """Populate os.environ from a .env file without overriding a real variable."""
    try:
        from dotenv import load_dotenv  # type: ignore
    except ImportError:
        pass
    else:
        load_dotenv(path, override=False)
        return

    try:
        with open(path, "r", encoding="utf-8") as handle:
            lines = handle.readlines()
    except OSError:
        return

    for line in lines:
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        # A variable already present in the real environment always wins, so a
        # container's configuration is never overwritten by a checked-in file.
        os.environ.setdefault(key, value)


ENV_FILE = Path(os.environ.get("DJANGO_ENV_FILE", BASE_DIR / ".env"))
if ENV_FILE.is_file():
    _load_env_file(ENV_FILE)


def env_bool(name, default=False):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


def env_int(name, default):
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return int(default)


def env_list(name, default=""):
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-x2fm@r%#6g_%ij3q%iesk42pa2o@)zkq53e$h74hb+b^w*0ct4',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

# --- PHI key material ------------------------------------------------------
#
# The SSN pepper is deliberately its own setting. It used to be SECRET_KEY
# itself, which coupled two rotation schedules that have nothing to do with
# each other: rotating SECRET_KEY is a routine response to a leaked deployment,
# and doing it would have re-digested every stored SSN fingerprint under a new
# key. Nothing would have failed loudly — member matching would simply have
# stopped matching and started creating duplicate people.
#
# It defaults to SECRET_KEY so an existing database keeps resolving. Set
# SSN_PEPPER explicitly before the two ever need to move apart; changing it
# afterwards requires re-deriving every fingerprint from plaintext, which is
# only possible while the plaintext column is still populated.
SSN_PEPPER = os.environ.get('SSN_PEPPER', '') or SECRET_KEY

if not DEBUG:
    # A production process must not fall back to the committed development key
    # for either value. Failing at import is the point: a silent fallback here
    # means PHI protected by a secret that is in the repository.
    from django.core.exceptions import ImproperlyConfigured

    if 'django-insecure-' in SECRET_KEY:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set to a real secret when DEBUG is off.'
        )
    if 'django-insecure-' in str(SSN_PEPPER):
        raise ImproperlyConfigured(
            'SSN_PEPPER must be set to a real secret when DEBUG is off; it keys the '
            'HMAC that identifies members without their plaintext SSN.'
        )

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver')

# The Vite dev server runs on its own origin. Everything below keeps the session
# cookie usable across that origin without loosening anything in production.
FRONTEND_ORIGINS = env_list(
    'FRONTEND_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174',
)

CSRF_TRUSTED_ORIGINS = list(FRONTEND_ORIGINS)

CORS_ALLOWED_ORIGINS = list(FRONTEND_ORIGINS)
CORS_ALLOW_CREDENTIALS = env_bool('CORS_ALLOW_CREDENTIALS', True)

# Session and CSRF cookies must survive a cross-origin XHR from the dev server.
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # the SPA reads this cookie to set X-CSRFToken
SESSION_COOKIE_AGE = env_int('SESSION_COOKIE_AGE', 60 * 60 * 8)

# Off by default now. It was on so that an active user's session kept sliding
# forward, which is a reasonable thing to want - but it makes every single
# request a database write, and the conversion screen polls job status while
# work is running. That turned a progress bar into several session-table writes
# per second, contending with the background worker for SQLite's single writer.
# Sessions still expire on SESSION_COOKIE_AGE from login; set
# SESSION_SAVE_EVERY_REQUEST=1 to restore sliding expiry if a client asks for it.
SESSION_SAVE_EVERY_REQUEST = env_bool('SESSION_SAVE_EVERY_REQUEST', False)


# Application definition

INSTALLED_APPS = ([
    'corsheaders',
] if HAS_CORS else []) + [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    'files',
    'mapping',
    'conversion',
    'edi',
    'members',
    'users',
]

MIDDLEWARE = ([
    'corsheaders.middleware.CorsMiddleware',
] if HAS_CORS else []) + [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite by default so the project runs with no external service. Set
# POSTGRES_DB (and friends) to point the same code at Postgres for staging or
# production; nothing else in the project needs to change.
if os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': 60,
        }
    }
else:
    # SQLite is the supported database for this deployment. The path is
    # configurable so a container can mount the file on a volume; nothing else
    # about the engine changes.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(os.environ.get('SQLITE_PATH', BASE_DIR / 'db.sqlite3')),
            'OPTIONS': {
                'timeout': env_int('SQLITE_TIMEOUT', 30),
                # WAL lets the read-heavy dashboard queries run while an upload
                # is still writing member rows, which is the shape of every
                # concurrent request this portal actually sees.
                # synchronous=NORMAL is the documented and safe pairing with
                # WAL: a commit no longer fsyncs, and the only exposure is that
                # the last few committed transactions could be lost if the
                # machine loses power (not if the process crashes - WAL still
                # covers that). For a portal that re-derives its member tables
                # from files it still holds on disk, that trade is worth
                # roughly a third of the sync's wall clock. Set
                # SQLITE_SYNCHRONOUS=FULL to give it back.
                'init_command': (
                    'PRAGMA journal_mode=WAL;'
                    ' PRAGMA foreign_keys=ON;'
                    ' PRAGMA synchronous={sync};'
                    ' PRAGMA temp_store=MEMORY;'
                ).format(sync=os.environ.get('SQLITE_SYNCHRONOUS', 'NORMAL')),
                # ---------------------------------------------------------
                # BEGIN IMMEDIATE, not BEGIN DEFERRED. This one word is the
                # difference between a member sync that completes and one that
                # logs "database is locked" a thousand times.
                #
                # A deferred transaction takes a shared read lock first and
                # upgrades to a write lock when it first writes. If any other
                # connection has written in between, SQLite returns SQLITE_BUSY
                # *immediately* and does not invoke the busy handler at all -
                # deliberately, because waiting there could deadlock two
                # upgraders against each other. So `timeout` above, all thirty
                # seconds of it, simply does not apply to the one case that
                # actually happens here: a background sync writing while a
                # polling request writes a session row.
                #
                # IMMEDIATE takes the write lock at BEGIN, where the busy
                # handler does apply, so a contending writer waits its turn
                # instead of failing instantly.
                # ---------------------------------------------------------
                'transaction_mode': os.environ.get('SQLITE_TRANSACTION_MODE', 'IMMEDIATE'),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = os.environ.get("DJANGO_MEDIA_URL", "/media/")

MEDIA_ROOT = Path(os.environ.get("DJANGO_MEDIA_ROOT", BASE_DIR / "media"))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- 834 converter settings -------------------------------------------------

# Where converted workbooks land. Kept under MEDIA_ROOT but in its own tree so
# generated output is never mistaken for a client-supplied source file.
GENERATED_SUBDIR = "generated"

# Refuse uploads larger than this outright rather than discovering the problem
# after the request has already consumed the memory.
MAX_834_UPLOAD_BYTES = env_int("MAX_834_UPLOAD_BYTES", 200 * 1024 * 1024)

# Never let a multipart upload be buffered entirely in RAM; 834 files are large.
FILE_UPLOAD_MAX_MEMORY_SIZE = env_int("FILE_UPLOAD_MAX_MEMORY_SIZE", 2 * 1024 * 1024)
DATA_UPLOAD_MAX_MEMORY_SIZE = env_int("DATA_UPLOAD_MAX_MEMORY_SIZE", 5 * 1024 * 1024)

# Django's own ceiling on a multipart body. It was left at the framework default
# of 2.5 MB while MAX_834_UPLOAD_BYTES advertised 200 MB, so a large 834 was
# refused by the middleware with a generic error long before the size check in
# the upload view could produce a useful message. Keep the two aligned, with a
# megabyte of slack for the multipart envelope itself.
DATA_UPLOAD_MAX_MEMORY_SIZE = max(DATA_UPLOAD_MAX_MEMORY_SIZE, 5 * 1024 * 1024)
FILE_UPLOAD_MAX_NUMBER_FIELDS = env_int("FILE_UPLOAD_MAX_NUMBER_FIELDS", 1000)

# The date format the portal writes and displays everywhere: workbook cells,
# API output and the browser. Kept in one place so a future change is one edit.
DISPLAY_DATE_FORMAT = os.environ.get("DISPLAY_DATE_FORMAT", "%m-%d-%Y")
EXCEL_DATE_FORMAT = os.environ.get("EXCEL_DATE_FORMAT", "MM-DD-YYYY")

# --- Background work -------------------------------------------------------
#
# Validation and conversion run off the request thread. See
# edi/services/runner.py for why this is a thread pool and not Celery.
#
# EDI_WORKER_THREADS is small deliberately: conversion is CPU-bound inside
# openpyxl and the member sync is I/O-bound on the database, so running many at
# once on one box makes each of them slower without finishing any sooner. Raise
# it only alongside a real measurement.
EDI_WORKER_THREADS = env_int("EDI_WORKER_THREADS", 2)

# Run jobs inline instead of on the pool.
#
# On under the test runner, and only there by default. Django's TestCase wraps
# each test in a transaction that a worker thread's own connection cannot see,
# so a threaded job in a test either deadlocks or asserts against an empty
# database - neither of which says anything about the code under test. Inline
# execution keeps the tests testing the pipeline rather than the scheduler.
#
# It is also a genuine escape hatch: set EDI_RUN_JOBS_INLINE=1 to reproduce a
# conversion in the foreground with a stack trace when something is wrong in
# production.
EDI_RUN_JOBS_INLINE = env_bool("EDI_RUN_JOBS_INLINE", False) or any(
    arg in ("test", "pytest") for arg in sys.argv
)

# A RUNNING job that has not reported in for this long is treated as abandoned
# and its file is released. Must be comfortably larger than the heartbeat.
EDI_JOB_STALE_SECONDS = env_int("EDI_JOB_STALE_SECONDS", 180)
EDI_JOB_HEARTBEAT_SECONDS = env_int("EDI_JOB_HEARTBEAT_SECONDS", 5)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"plain": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "plain"}},
    "loggers": {
        "edi": {"handlers": ["console"], "level": os.environ.get("EDI_LOG_LEVEL", "INFO")},
        "django.request": {"handlers": ["console"], "level": "ERROR"},
    },
}

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    X_FRAME_OPTIONS = "DENY"
