"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

try:  # optional, only needed for the split-origin dev setup
    import corsheaders  # noqa: F401
    HAS_CORS = True
except ImportError:  # pragma: no cover
    HAS_CORS = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-x2fm@r%#6g_%ij3q%iesk42pa2o@)zkq53e$h74hb+b^w*0ct4',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

# --- PHI key material ------------------------------------------------------
#
# The SSN pepper is deliberately its own setting. It used to be SECRET_KEY
# itself, which coupled two rotation schedules that have nothing to do with
# each other: rotating SECRET_KEY is a routine response to a leaked deployment,
# and doing it would have re-digested every stored SSN fingerprint under a new
# key. Nothing would have failed loudly — member matching would simply have
# stopped matching and started creating duplicate people.
#
# It defaults to SECRET_KEY so an existing database keeps resolving. Set
# SSN_PEPPER explicitly before the two ever need to move apart; changing it
# afterwards requires re-deriving every fingerprint from plaintext, which is
# only possible while the plaintext column is still populated.
SSN_PEPPER = os.environ.get('SSN_PEPPER', '') or SECRET_KEY

if not DEBUG:
    # A production process must not fall back to the committed development key
    # for either value. Failing at import is the point: a silent fallback here
    # means PHI protected by a secret that is in the repository.
    from django.core.exceptions import ImproperlyConfigured

    if 'django-insecure-' in SECRET_KEY:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set to a real secret when DEBUG is off.'
        )
    if 'django-insecure-' in str(SSN_PEPPER):
        raise ImproperlyConfigured(
            'SSN_PEPPER must be set to a real secret when DEBUG is off; it keys the '
            'HMAC that identifies members without their plaintext SSN.'
        )

ALLOWED_HOSTS = [
    h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',') if h
]

# The Vite dev server runs on its own origin. Everything below keeps the session
# cookie usable across that origin without loosening anything in production.
FRONTEND_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        'FRONTEND_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174',
    ).split(',')
    if o.strip()
]

CSRF_TRUSTED_ORIGINS = list(FRONTEND_ORIGINS)

CORS_ALLOWED_ORIGINS = list(FRONTEND_ORIGINS)
CORS_ALLOW_CREDENTIALS = True

# Session and CSRF cookies must survive a cross-origin XHR from the dev server.
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # the SPA reads this cookie to set X-CSRFToken
SESSION_COOKIE_AGE = 60 * 60 * 8
SESSION_SAVE_EVERY_REQUEST = True


# Application definition

INSTALLED_APPS = ([
    'corsheaders',
] if HAS_CORS else []) + [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    'files',
    'mapping',
    'conversion',
    'edi',
    'members',
    'users',
]

MIDDLEWARE = ([
    'corsheaders.middleware.CorsMiddleware',
] if HAS_CORS else []) + [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite by default so the project runs with no external service. Set
# POSTGRES_DB (and friends) to point the same code at Postgres for staging or
# production; nothing else in the project needs to change.
if os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': 60,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {'timeout': 30},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- 834 converter settings -------------------------------------------------

# Where converted workbooks land. Kept under MEDIA_ROOT but in its own tree so
# generated output is never mistaken for a client-supplied source file.
GENERATED_SUBDIR = "generated"

# Refuse uploads larger than this outright rather than discovering the problem
# after the request has already consumed the memory.
MAX_834_UPLOAD_BYTES = int(os.environ.get("MAX_834_UPLOAD_BYTES", 200 * 1024 * 1024))

# Never let a multipart upload be buffered entirely in RAM; 834 files are large.
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"plain": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "plain"}},
    "loggers": {
        "edi": {"handlers": ["console"], "level": os.environ.get("EDI_LOG_LEVEL", "INFO")},
        "django.request": {"handlers": ["console"], "level": "ERROR"},
    },
}

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    X_FRAME_OPTIONS = "DENY"
