# Generated by Django 5.2.17 on 2026-08-22 12:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner_id', 'mapping_name', '-version'),
            },
        ),
        migrations.CreateModel(
            name='SegmentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z][A-Z0-9]{1,2}$', 'Segment id is two or three uppercase alphanumerics, e.g. NM1, DMG, N3.')])),
                ('element_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[A-Z][A-Z0-9]{1,2}\\d{2}$', 'Element code is the segment id followed by a two digit position, e.g. NM103.')])),
                ('description', models.CharField(max_length=120)),
                ('loop_id', models.CharField(blank=True, help_text='Implementation guide loop, e.g. 2000, 2100A, 2300.', max_length=8)),
                ('data_type', models.CharField(blank=True, help_text='AN, ID, DT, N0 and so on.', max_length=12)),
                ('max_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_composite', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('segment_name', 'element_code'),
                'constraints': [models.UniqueConstraint(fields=('segment_name', 'element_code', 'loop_id'), name='uniq_segment_element_loop')],
            },
        ),
        migrations.CreateModel(
            name='MappingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_column', models.CharField(help_text='Header text as it appears in the workbook, e.g. DEP LAST NAME.', max_length=64)),
                ('column_order', models.PositiveSmallIntegerField()),
                ('qualifier_element', models.CharField(blank=True, help_text='Element that disambiguates the occurrence, e.g. NM101 or DTP01.', max_length=6)),
                ('qualifier_value', models.CharField(blank=True, help_text='Required value of the qualifier element, e.g. IL for the insured, 348 for a benefit begin date.', max_length=12)),
                ('component_index', models.PositiveSmallIntegerField(blank=True, help_text='1-based sub-element position when the element is composite.', null=True)),
                ('occurrence', models.PositiveSmallIntegerField(default=1, help_text='Which matching occurrence to take when the segment legitimately repeats.')),
                ('applies_to', models.CharField(choices=[('BOTH', 'Subscriber and dependent'), ('SUB', 'Subscriber only'), ('DEP', 'Dependent only')], default='BOTH', max_length=8)),
                ('transform', models.CharField(choices=[('NONE', 'Raw value'), ('DATE_MDY', 'CCYYMMDD to MM/DD/YYYY'), ('DATE_ISO', 'CCYYMMDD to YYYY-MM-DD'), ('SSN_DASHED', '9 digits to NNN-NN-NNNN'), ('SSN_LAST4', 'Mask to last four digits'), ('UPPER', 'Uppercase'), ('TITLE', 'Title case'), ('PHONE', '10 digits to (NNN) NNN-NNNN')], default='NONE', max_length=12)),
                ('default_value', models.CharField(blank=True, max_length=120)),
                ('is_required', models.BooleanField(default=False, help_text='Parser raises a warning when the source element is absent.')),
                ('mapping_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mapping.mappingtemplate')),
                ('segment_element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping_details', to='mapping.segmentelement')),
            ],
            options={
                'ordering': ('mapping_template_id', 'column_order'),
            },
        ),
        migrations.AddConstraint(
            model_name='mappingtemplate',
            constraint=models.UniqueConstraint(fields=('owner', 'mapping_name', 'version'), name='uniq_template_name_version_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='mappingtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='one_default_template_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='mappingdetail',
            constraint=models.UniqueConstraint(fields=('mapping_template', 'excel_column'), name='uniq_excel_column_per_template'),
        ),
        migrations.AddConstraint(
            model_name='mappingdetail',
            constraint=models.UniqueConstraint(fields=('mapping_template', 'column_order'), name='uniq_column_order_per_template'),
        ),
        migrations.AddConstraint(
            model_name='mappingdetail',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('qualifier_element', ''), ('qualifier_value', '')), models.Q(models.Q(('qualifier_element', ''), _negated=True), models.Q(('qualifier_value', ''), _negated=True)), _connector='OR'), name='qualifier_element_and_value_together', violation_error_message='Give both a qualifier element and a qualifier value, or neither.'),
        ),
    ]
