# Generated by Django 5.2.17 on 2026-08-25 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mappingtemplate',
            name='uniq_template_name_version_per_owner',
        ),
        migrations.RemoveConstraint(
            model_name='mappingtemplate',
            name='one_default_template_per_owner',
        ),
        migrations.AddField(
            model_name='mappingtemplate',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Health plan this record belongs to. Null on rows written before tenancy existed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapping_templates', to='users.client'),
        ),
        migrations.AddField(
            model_name='mappingtemplate',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Set the moment this version is used by a completed conversion. A locked version is never edited again; an edit clones it to the next version, so ConversionHistory.mapping_version keeps meaning what it said at the time.', null=True),
        ),
        migrations.AddConstraint(
            model_name='mappingtemplate',
            constraint=models.UniqueConstraint(fields=('owner', 'client', 'mapping_name', 'version'), name='uniq_template_name_version_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='mappingtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner', 'client'), name='one_default_template_per_owner'),
        ),
    ]
