# Generated by Django 5.2.17 on 2026-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_remove_mappingtemplate_uniq_template_name_version_per_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingdetail',
            name='transform',
            field=models.CharField(choices=[('NONE', 'Raw value'), ('DATE_MDY', 'CCYYMMDD to MM-DD-YYYY'), ('DATE_MDY_SLASH', 'CCYYMMDD to MM/DD/YYYY (legacy)'), ('DATE_ISO', 'CCYYMMDD to YYYY-MM-DD'), ('SSN', '9 digits, leading zeros kept, written as text'), ('SSN_DASHED', '9 digits to NNN-NN-NNNN'), ('SSN_LAST4', 'Mask to last four digits'), ('UPPER', 'Uppercase'), ('LOWER', 'Lowercase'), ('TITLE', 'Title case'), ('PHONE', '10 digits to (NNN) NNN-NNNN'), ('TEXT', 'Force text, never interpreted as a number')], default='NONE', max_length=16),
        ),
    ]
