# Generated by Django 5.2.17 on 2026-08-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_alter_mappingdetail_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtemplate',
            name='column_layout',
            field=models.JSONField(blank=True, default=list, help_text='Every column of the workbook, in order, mapped or not. Kept apart from the MappingDetail rows because the two answer different questions: a detail says how a column is filled, and this says the column exists at all. Columns such as LOCAL and CLASS are deliberately unmapped and filled in downstream by hand, and un-mapping a column must leave it on the screen to be re-mapped rather than deleting it from the layout.'),
        ),
    ]
