# Generated by Django 5.2.17 on 2026-08-22 12:02

import django.core.validators
import django.db.models.deletion
import files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_file', models.FileField(max_length=500, upload_to=files.models.upload_to_834)),
                ('file_size_bytes', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content_sha256', models.CharField(db_index=True, help_text='Checksum of the raw bytes. Used to detect a re-upload of an already processed file.', max_length=64)),
                ('interchange_control_number', models.CharField(blank=True, help_text='ISA13', max_length=9)),
                ('group_control_number', models.CharField(blank=True, help_text='GS06', max_length=9)),
                ('transaction_set_control_number', models.CharField(blank=True, help_text='ST02', max_length=9)),
                ('sender_id', models.CharField(blank=True, help_text='ISA06', max_length=15)),
                ('receiver_id', models.CharField(blank=True, help_text='ISA08', max_length=15)),
                ('sponsor_name', models.CharField(blank=True, help_text='Loop 1000A N102', max_length=60)),
                ('file_date', models.DateField(blank=True, db_index=True, help_text='Business date the file represents, taken from BGN03 or GS04. Daily comparison keys on this, never on uploaded_at — a file can arrive late or be re-uploaded.', null=True)),
                ('is_full_file', models.BooleanField(help_text='True when the file is a full-file audit refresh (INS03=030 throughout), False for change-only files.', null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing'), ('PARSED', 'Parsed'), ('FAILED', 'Failed'), ('QUARANTINED', 'Quarantined')], db_index=True, default='PENDING', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('segment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('member_loop_count', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_filename', models.CharField(max_length=255)),
                ('stored_file', models.FileField(max_length=500, upload_to=files.models.upload_to_excel)),
                ('file_format', models.CharField(choices=[('XLSX', 'Excel workbook'), ('CSV', 'Comma separated')], default='XLSX', max_length=8)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_files', to='files.uploadedfile')),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['owner', '-file_date'], name='uf_owner_filedate_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['owner', 'processing_status'], name='uf_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploadedfile',
            constraint=models.UniqueConstraint(fields=('owner', 'content_sha256'), name='uniq_upload_per_owner_checksum'),
        ),
        migrations.AddConstraint(
            model_name='uploadedfile',
            constraint=models.CheckConstraint(condition=models.Q(('processing_finished_at__isnull', True), ('processing_started_at__isnull', False), _connector='OR'), name='uf_finished_requires_started'),
        ),
        migrations.AddIndex(
            model_name='generatedfile',
            index=models.Index(fields=['owner', '-generated_at'], name='gf_owner_generated_idx'),
        ),
    ]
