# Generated by Django 5.2.17 on 2026-08-25 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uploadedfile',
            name='uniq_upload_per_owner_checksum',
        ),
        migrations.AddField(
            model_name='generatedfile',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Health plan this record belongs to. Null on rows written before tenancy existed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_files', to='users.client'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Health plan this record belongs to. Null on rows written before tenancy existed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to='users.client'),
        ),
        migrations.AddConstraint(
            model_name='uploadedfile',
            constraint=models.UniqueConstraint(fields=('owner', 'client', 'content_sha256'), name='uniq_upload_per_owner_checksum'),
        ),
    ]
