# Generated by Django 5.2.17 on 2026-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_uploadedfile_uniq_upload_per_owner_checksum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='conversion_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='converted_at',
            field=models.DateTimeField(blank=True, help_text='When the most recent workbook was generated from this file.', null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='When 834 validation last completed, pass or fail.', null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, help_text='Structural errors from the last validation run. Empty list means it passed.'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='validation_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('CONVERTING', 'Converting'), ('CONVERTED', 'Converted'), ('FAILED', 'Failed'), ('QUARANTINED', 'Quarantined'), ('PENDING', 'Pending (legacy alias for Uploaded)'), ('PARSING', 'Parsing (legacy alias for Validating)'), ('PARSED', 'Parsed (legacy alias for Validated)')], db_index=True, default='UPLOADED', max_length=16),
        ),
    ]
