# Generated by Django 5.2.17 on 2026-08-22 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('SUB', 'Subscriber'), ('DEP', 'Dependent')], db_index=True, max_length=3)),
                ('relationship_code', models.CharField(choices=[('01', 'Spouse'), ('19', 'Child'), ('18', 'Self'), ('17', 'Stepson or stepdaughter'), ('10', 'Foster child'), ('15', 'Ward'), ('53', 'Life partner'), ('G8', 'Other relationship')], default='18', max_length=2)),
                ('member_id', models.CharField(blank=True, help_text='Carrier or sponsor assigned identifier, NM109 of the insured loop.', max_length=80)),
                ('subscriber_number', models.CharField(blank=True, help_text='REF*0F subscriber number, carried on dependents as well. Named subscriber_number rather than subscriber_id because the self foreign key already owns that attribute.', max_length=80)),
                ('group_number', models.CharField(blank=True, help_text='REF*1L policy or group number.', max_length=50)),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(max_length=60)),
                ('name_suffix', models.CharField(blank=True, max_length=10)),
                ('ssn', models.CharField(blank=True, help_text='Plaintext today for parity with the source file. Move this to an application layer encrypted field or a token before production; see the design note on PHI at rest.', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Store SSN as nine digits with no dashes.')])),
                ('ssn_fingerprint', models.CharField(blank=True, db_index=True, help_text='Keyed HMAC of the SSN. Match on this, never on the plaintext column.', max_length=64)),
                ('gender_code', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, help_text='Union local or division, mapped per sponsor.', max_length=30)),
                ('plan_code', models.CharField(blank=True, max_length=30)),
                ('class_code', models.CharField(blank=True, db_column='class_code', help_text="The Excel column is CLASS. 'class' is a Python keyword, so the attribute is class_code.", max_length=30)),
                ('address1', models.CharField(blank=True, max_length=55)),
                ('address2', models.CharField(blank=True, max_length=55)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Two letter uppercase state or territory code.')])),
                ('postal_code', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}(\\d{4})?$', 'ZIP is five or nine digits, no dash.')])),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Store phone as ten digits with no punctuation.')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('coverage_status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated'), ('COBRA', 'COBRA'), ('SURVIVING', 'Surviving insured'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', help_text='Denormalised from the open eligibility span. Recomputed on write, never edited by hand.', max_length=12)),
                ('benefit_status_code', models.CharField(blank=True, help_text='INS05.', max_length=2)),
                ('employment_status_code', models.CharField(blank=True, help_text='INS08.', max_length=2)),
                ('student_status_code', models.CharField(blank=True, help_text='INS09.', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_seen_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members_first_seen', to='files.uploadedfile')),
                ('last_seen_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members_last_seen', to='files.uploadedfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(blank=True, help_text='Null on a subscriber row, set on every dependent row.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='members.member')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='CustodialParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=35)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('address1', models.CharField(blank=True, max_length=55)),
                ('address2', models.CharField(blank=True, max_length=55)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Two letter uppercase state or territory code.')])),
                ('postal_code', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}(\\d{4})?$', 'ZIP is five or nine digits, no dash.')])),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Store phone as ten digits with no punctuation.')])),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custodial_parent', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberDailyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField(db_index=True, help_text='Copied from UploadedFile.file_date at write time.')),
                ('change_type', models.CharField(choices=[('ADDED', 'New this file'), ('UNCHANGED', 'Present, no change'), ('CHANGED', 'Present, demographic or plan change'), ('REINSTATED', 'Present, coverage reopened'), ('TERMINATED', 'Present, coverage closed')], default='UNCHANGED', max_length=12)),
                ('changed_fields', models.JSONField(blank=True, default=dict, help_text='Field level diff, e.g. {"plan_code": ["PPO", "HDHP"]}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_statuses', to='members.member')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_statuses', to='files.uploadedfile')),
            ],
            options={
                'verbose_name_plural': 'member daily statuses',
                'ordering': ('-status_date', 'member_id'),
            },
        ),
        migrations.CreateModel(
            name='MemberEligibilityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_line_code', models.CharField(default='HLT', help_text='HD03, e.g. HLT medical, DEN dental, VIS vision.', max_length=3)),
                ('plan_code', models.CharField(blank=True, max_length=30)),
                ('class_code', models.CharField(blank=True, max_length=30)),
                ('effective_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, help_text='Null means the span is open.', null=True)),
                ('maintenance_type_code', models.CharField(blank=True, choices=[('001', 'Change'), ('021', 'Addition'), ('024', 'Cancellation or termination'), ('025', 'Reinstatement'), ('030', 'Audit or compare')], help_text='INS03.', max_length=3)),
                ('maintenance_reason_code', models.CharField(blank=True, help_text='INS04.', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_history', to='members.member')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_rows', to='files.uploadedfile')),
            ],
            options={
                'verbose_name_plural': 'member eligibility history',
                'ordering': ('member_id', 'insurance_line_code', '-effective_date'),
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['owner', 'last_name', 'first_name'], name='mem_owner_name_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['owner', 'member_type', 'coverage_status'], name='mem_owner_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['subscriber', 'member_type'], name='mem_subscriber_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('member_id', ''), _negated=True), fields=('owner', 'member_id'), name='uniq_member_id_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('member_type', 'SUB'), ('subscriber__isnull', True)), models.Q(('member_type', 'DEP'), ('subscriber__isnull', False)), _connector='OR'), name='dependent_requires_subscriber', violation_error_message='A subscriber row has no subscriber link, a dependent row must have one.'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(('date_of_death__isnull', True), ('date_of_birth__isnull', True), ('date_of_death__gte', models.F('date_of_birth')), _connector='OR'), name='death_not_before_birth'),
        ),
        migrations.AddIndex(
            model_name='memberdailystatus',
            index=models.Index(fields=['status_date', 'change_type'], name='mds_date_change_idx'),
        ),
        migrations.AddIndex(
            model_name='memberdailystatus',
            index=models.Index(fields=['member', '-status_date'], name='mds_member_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberdailystatus',
            constraint=models.UniqueConstraint(fields=('member', 'status_date'), name='uniq_member_status_per_date'),
        ),
        migrations.AddIndex(
            model_name='membereligibilityhistory',
            index=models.Index(fields=['member', 'insurance_line_code', '-effective_date'], name='elig_member_line_idx'),
        ),
        migrations.AddIndex(
            model_name='membereligibilityhistory',
            index=models.Index(fields=['termination_date'], name='elig_open_span_idx'),
        ),
        migrations.AddConstraint(
            model_name='membereligibilityhistory',
            constraint=models.UniqueConstraint(fields=('member', 'insurance_line_code', 'effective_date'), name='uniq_span_start_per_member_line'),
        ),
        migrations.AddConstraint(
            model_name='membereligibilityhistory',
            constraint=models.CheckConstraint(condition=models.Q(('termination_date__isnull', True), ('termination_date__gte', models.F('effective_date')), _connector='OR'), name='term_not_before_effective', violation_error_message='Termination date cannot precede the effective date.'),
        ),
    ]
