# Generated by Django 4.2.17 on 2026-08-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ssn',
            field=models.CharField(blank=True, help_text='Plaintext today for parity with the source file. Move this to an application layer encrypted field or a token before production; see the design note on PHI at rest.', max_length=50),
        ),
    ]
