# Generated by Django 5.2.17 on 2026-08-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ssn',
            field=models.CharField(blank=True, help_text='Plaintext today for parity with the source file. Move this to an application layer encrypted field or a token before production; see the design note on PHI at rest. Normalised to nine digits on save; SSN_DIGITS is applied in clean() rather than as a field validator because migration 0002 widened this column and the model had drifted from it.', max_length=50),
        ),
    ]
