# Generated by Django 5.2.17 on 2026-08-25 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_uploadedfile_uniq_upload_per_owner_checksum_and_more'),
        ('members', '0003_alter_member_ssn'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='member',
            name='uniq_member_id_per_owner',
        ),
        migrations.RemoveConstraint(
            model_name='member',
            name='dependent_requires_subscriber',
        ),
        migrations.RemoveConstraint(
            model_name='memberdailystatus',
            name='uniq_member_status_per_date',
        ),
        migrations.AddField(
            model_name='member',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Health plan this record belongs to. Null on rows written before tenancy existed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='users.client'),
        ),
        migrations.AddField(
            model_name='member',
            name='subscriber_pending',
            field=models.BooleanField(db_index=True, default=False, help_text='This dependent arrived before its subscriber loop and is waiting to be linked. The member_type stays DEP; it is never rewritten to SUB to satisfy a constraint, because the relink pass only looks at DEP rows and a row flipped to SUB would never come back.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subscriber',
            field=models.ForeignKey(blank=True, help_text='Null on a subscriber row. Set on a dependent row once the subscriber is known; null with subscriber_pending=True while it is not.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='members.member'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['owner', 'ssn_fingerprint'], name='mem_owner_ssn_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['owner', 'member_id'], name='mem_owner_memberid_idx'),
        ),
        migrations.AddIndex(
            model_name='memberdailystatus',
            index=models.Index(fields=['uploaded_file', 'member'], name='mds_file_member_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('member_id', ''), _negated=True), fields=('owner', 'client', 'member_id'), name='uniq_member_id_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('member_type', 'SUB'), ('subscriber__isnull', True)), models.Q(('member_type', 'DEP'), ('subscriber__isnull', False)), models.Q(('member_type', 'DEP'), ('subscriber_pending', True)), _connector='OR'), name='dependent_requires_subscriber', violation_error_message='A subscriber row has no subscriber link; a dependent row needs one unless it is explicitly flagged as pending linkage.'),
        ),
        migrations.AddConstraint(
            model_name='memberdailystatus',
            constraint=models.UniqueConstraint(fields=('member', 'status_date', 'uploaded_file'), name='uniq_member_status_per_date'),
        ),
    ]
