# Generated by Django 5.2.17 on 2026-08-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_uniq_member_id_per_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ssn_last4',
            field=models.CharField(blank=True, help_text='The only part of an SSN any screen displays. Stored separately so masking, searching and the roster dropdown all work without the plaintext column, which can then be purged. See the purge_plaintext_ssn command.', max_length=4),
        ),
    ]
