# Generated by Django 5.2.17 on 2026-08-25 12:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadedfile_conversion_error_and_more'),
        ('members', '0006_backfill_ssn_last4'),
        ('users', '0002_backfill_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(blank=True, help_text='Exactly nine digits, no punctuation, leading zeros preserved. Normalised on save. Unique per tenant when present; blank is allowed because a sponsor is entitled to send a member with no SSN, and SQLite would treat several blanks as a collision under a plain unique index.', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Store SSN as nine digits with no dashes.')])),
                ('ssn_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ssn_last4', models.CharField(blank=True, max_length=4)),
                ('member_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('first_name', models.CharField(blank=True, max_length=35)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('plan', models.CharField(blank=True, max_length=30)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('01', 'Spouse'), ('19', 'Child'), ('18', 'Self'), ('17', 'Stepson or stepdaughter'), ('10', 'Foster child'), ('15', 'Ward'), ('53', 'Life partner'), ('G8', 'Other relationship')], default='19', max_length=2)),
                ('client', models.ForeignKey(blank=True, help_text='Health plan this record belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.client')),
                ('first_source_file', models.ForeignKey(blank=True, help_text='The file this person first appeared in. Never overwritten.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.uploadedfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(blank=True, help_text='Most recent 834 this person was carried in. The full list is in EnrollmentRecord — this column is the newest one, not the only one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.uploadedfile')),
                ('source_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependant_record', to='members.member')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(blank=True, help_text='Exactly nine digits, no punctuation, leading zeros preserved. Normalised on save. Unique per tenant when present; blank is allowed because a sponsor is entitled to send a member with no SSN, and SQLite would treat several blanks as a collision under a plain unique index.', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Store SSN as nine digits with no dashes.')])),
                ('ssn_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ssn_last4', models.CharField(blank=True, max_length=4)),
                ('member_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('first_name', models.CharField(blank=True, max_length=35)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('plan', models.CharField(blank=True, max_length=30)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Health plan this record belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.client')),
                ('first_source_file', models.ForeignKey(blank=True, help_text='The file this person first appeared in. Never overwritten.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.uploadedfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(blank=True, help_text='Most recent 834 this person was carried in. The full list is in EnrollmentRecord — this column is the newest one, not the only one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.uploadedfile')),
                ('source_member', models.OneToOneField(blank=True, help_text='Link back to the operational person row this was projected from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber_record', to='members.member')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_date', models.DateField(blank=True, db_index=True, null=True)),
                ('plan', models.CharField(blank=True, max_length=30)),
                ('insurance_line_code', models.CharField(blank=True, max_length=3)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('maintenance_type_code', models.CharField(blank=True, max_length=3)),
                ('relationship', models.CharField(blank=True, max_length=2)),
                ('member_type', models.CharField(choices=[('SUB', 'Subscriber'), ('DEP', 'Dependent')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.client')),
                ('dependant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='members.dependant')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_records', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_records', to='files.uploadedfile')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='members.subscriber')),
            ],
            options={
                'ordering': ('-file_date', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='dependant',
            name='subscriber',
            field=models.ForeignKey(blank=True, help_text='Null only while the dependant is waiting for its subscriber loop to arrive. An 834 does not promise the subscriber comes first.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='members.subscriber'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['owner', 'last_name', 'first_name'], name='sub_owner_name_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['owner', 'ssn_fingerprint'], name='sub_owner_ssn_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('ssn', ''), _negated=True), fields=('owner', 'client', 'ssn'), name='uniq_subscriber_ssn_per_tenant', violation_error_message='A subscriber with this SSN already exists for this client.'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('member_id', ''), _negated=True), fields=('owner', 'client', 'member_id'), name='uniq_subscriber_member_id_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='enrollmentrecord',
            index=models.Index(fields=['subscriber', '-file_date'], name='enr_sub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentrecord',
            index=models.Index(fields=['dependant', '-file_date'], name='enr_dep_date_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentrecord',
            index=models.Index(fields=['source_file'], name='enr_file_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('dependant__isnull', True), ('subscriber__isnull', False)), models.Q(('dependant__isnull', False), ('subscriber__isnull', True)), _connector='OR'), name='enrollment_belongs_to_exactly_one_person', violation_error_message='An enrollment record belongs to a subscriber or a dependant, not both and not neither.'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrecord',
            constraint=models.CheckConstraint(check=models.Q(('termination_date__isnull', True), ('effective_date__isnull', True), ('termination_date__gte', models.F('effective_date')), _connector='OR'), name='enr_term_not_before_effective'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('subscriber__isnull', False)), fields=('subscriber', 'source_file', 'insurance_line_code'), name='uniq_sub_enrollment_per_file_line'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('dependant__isnull', False)), fields=('dependant', 'source_file', 'insurance_line_code'), name='uniq_dep_enrollment_per_file_line'),
        ),
        migrations.AddIndex(
            model_name='dependant',
            index=models.Index(fields=['owner', 'last_name', 'first_name'], name='dep_owner_name_idx'),
        ),
        migrations.AddIndex(
            model_name='dependant',
            index=models.Index(fields=['owner', 'ssn_fingerprint'], name='dep_owner_ssn_idx'),
        ),
        migrations.AddIndex(
            model_name='dependant',
            index=models.Index(fields=['subscriber'], name='dep_subscriber_idx'),
        ),
        migrations.AddConstraint(
            model_name='dependant',
            constraint=models.UniqueConstraint(condition=models.Q(('ssn', ''), _negated=True), fields=('owner', 'client', 'ssn'), name='uniq_dependant_ssn_per_tenant', violation_error_message='A dependant with this SSN already exists for this client.'),
        ),
        migrations.AddConstraint(
            model_name='dependant',
            constraint=models.UniqueConstraint(condition=models.Q(('member_id', ''), _negated=True), fields=('owner', 'client', 'member_id'), name='uniq_dependant_member_id_per_tenant'),
        ),
    ]
