# Generated by Django 5.2.17 on 2026-08-26 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadedfile_conversion_error_and_more'),
        ('members', '0007_dependant_subscriber_enrollmentrecord_and_more'),
        ('users', '0002_backfill_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='content_digest',
            field=models.CharField(blank=True, help_text="Digest of the 834 loop that last wrote this row. When the next file carries the same digest for the same person, nothing about them has changed and the whole write path is skipped — which is what makes a repeated daily roster cheap. Blank means 'unknown, do the work'. Deliberately not indexed: it is only ever read by primary key.", max_length=64),
        ),
        migrations.CreateModel(
            name='MemberChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ssn_last4', models.CharField(blank=True, max_length=4)),
                ('sponsor_member_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('member_name', models.CharField(blank=True, max_length=120)),
                ('member_type', models.CharField(blank=True, choices=[('SUB', 'Subscriber'), ('DEP', 'Dependent')], max_length=3)),
                ('field_name', models.CharField(db_index=True, help_text='The model field that moved, e.g. plan_code. Rendered through a label map.', max_length=60)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('IDENTITY', 'Name or identifier'), ('DEMOGRAPHIC', 'Demographics'), ('ADDRESS', 'Address or contact'), ('PLAN', 'Plan or class'), ('COVERAGE', 'Coverage dates'), ('TERMINATION', 'Coverage terminated'), ('REINSTATEMENT', 'Coverage reinstated'), ('ENROLLMENT', 'New enrollment')], db_index=True, default='DEMOGRAPHIC', max_length=14)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('REVIEW', 'Worth a look'), ('CRITICAL', 'Needs action')], db_index=True, default='REVIEW', max_length=8)),
                ('previous_file_date', models.DateField(blank=True, null=True)),
                ('current_file_date', models.DateField(blank=True, db_index=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Why this was accepted or what was done about it.')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.client')),
                ('current_file', models.ForeignKey(help_text='The file that asserted the new value.', on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='files.uploadedfile')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='members.member')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_change_events', to=settings.AUTH_USER_MODEL)),
                ('previous_file', models.ForeignKey(blank=True, help_text='The file that last asserted the old value. Null when it predates this table.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.uploadedfile')),
            ],
            options={
                'ordering': ('-current_file_date', '-detected_at', 'sponsor_member_id'),
                'indexes': [models.Index(fields=['owner', 'client', '-current_file_date'], name='mce_owner_date_idx'), models.Index(fields=['owner', 'category', 'severity'], name='mce_cat_sev_idx'), models.Index(fields=['member', '-current_file_date'], name='mce_member_date_idx'), models.Index(fields=['current_file'], name='mce_file_idx'), models.Index(condition=models.Q(('acknowledged_at__isnull', True)), fields=['owner', '-detected_at'], name='mce_open_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'current_file', 'field_name'), name='uniq_change_per_member_file_field')],
            },
        ),
    ]
