# Generated by Django 5.2.17 on 2026-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadedfile_conversion_error_and_more'),
        ('members', '0008_member_content_digest_memberchangeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='membereligibilityhistory',
            name='effective_date_as_per_law',
            field=models.DateField(blank=True, help_text='FOM backdated.', null=True),
        ),
        migrations.AddField(
            model_name='membereligibilityhistory',
            name='termination_date_as_per_law',
            field=models.DateField(blank=True, help_text='EOM snapped term date. Null means open.', null=True),
        ),
        migrations.AddConstraint(
            model_name='membereligibilityhistory',
            constraint=models.CheckConstraint(condition=models.Q(('termination_date_as_per_law__isnull', True), ('termination_date_as_per_law__gte', models.F('effective_date_as_per_law')), _connector='OR'), name='term_not_before_effective_as_per_law', violation_error_message='Termination date as per law cannot precede the effective date as per law.'),
        ),
    ]
